#if !canImport(ObjectiveC)
import XCTest

extension DITranquillityTests_Build {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DITranquillityTests_Build = [
        ("test01_NotSetInitializer", test01_NotSetInitializer),
        ("test01_NotSetInitializerForClass", test01_NotSetInitializerForClass),
        ("test01_NotSetProtocol", test01_NotSetProtocol),
        ("test01_RegistrateOnlyRealization", test01_RegistrateOnlyRealization),
        ("test01_RegistrateWithOptional", test01_RegistrateWithOptional),
        ("test02_MultiplyRegistrateType", test02_MultiplyRegistrateType),
        ("test02_MultiplyRegistrateTypeWithDefault", test02_MultiplyRegistrateTypeWithDefault),
        ("test02_MultiplyRegistrateTypeWithName", test02_MultiplyRegistrateTypeWithName),
        ("test02_MultiplyRegistrateTypeWithTag", test02_MultiplyRegistrateTypeWithTag),
        ("test04_RecursiveTripleInit", test04_RecursiveTripleInit),
        ("test04_RecursiveTripleInitArray", test04_RecursiveTripleInitArray),
        ("test04_RecursiveTripleInitArrayWithCorrectLifetime", test04_RecursiveTripleInitArrayWithCorrectLifetime),
        ("test04_SelfInit", test04_SelfInit),
        ("test05_RecursiveTripleInitInject", test05_RecursiveTripleInitInject),
        ("test05_RecursiveTripleInitInjectIsCycle", test05_RecursiveTripleInitInjectIsCycle),
        ("test05_RecursiveTripleInitInjectIsCycleButLifetime", test05_RecursiveTripleInitInjectIsCycleButLifetime),
        ("test05_RecursiveTripleInitInjectOptional", test05_RecursiveTripleInitInjectOptional),
        ("test06_CycleWithoutInit", test06_CycleWithoutInit),
    ]
}

extension DITranquillityTests_Extensions {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DITranquillityTests_Extensions = [
        ("test01_Arguments", test01_Arguments),
        ("test02_DepthArguments", test02_DepthArguments),
        ("test03_OptionalArguments", test03_OptionalArguments),
        ("test04_NotSetOptionalArguments", test04_NotSetOptionalArguments),
    ]
}

extension DITranquillityTests_Lifetime {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DITranquillityTests_Lifetime = [
        ("test01_single", test01_single),
        ("test02_perApplication", test02_perApplication),
        ("test02_perApplicationSingle", test02_perApplicationSingle),
        ("test02_perApplicationWeakRelease", test02_perApplicationWeakRelease),
        ("test02_perApplicationWeakRetain", test02_perApplicationWeakRetain),
        ("test03_perContainer", test03_perContainer),
        ("test03_perContainerClean", test03_perContainerClean),
        ("test03_perContainerSingle", test03_perContainerSingle),
        ("test03_perContainerWeakRelease", test03_perContainerWeakRelease),
        ("test03_perContainerWeakRetain", test03_perContainerWeakRetain),
        ("test04_objectGraph", test04_objectGraph),
        ("test05_prototype", test05_prototype),
        ("test06_prototypeWithObjectGraph", test06_prototypeWithObjectGraph),
        ("test07_customScope", test07_customScope),
        ("test07_customWeakScope", test07_customWeakScope),
    ]
}

extension DITranquillityTests_MoreParameters {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DITranquillityTests_MoreParameters = [
        ("test01", test01),
        ("test02", test02),
        ("test03", test03),
        ("test04", test04),
        ("test05", test05),
        ("test06", test06),
        ("test07", test07),
        ("test08", test08),
        ("test09", test09),
        ("test10", test10),
        ("test11", test11),
        ("test12", test12),
        ("test13", test13),
        ("test14", test14),
        ("test15", test15),
        ("testMethod01", testMethod01),
        ("testMethod02", testMethod02),
        ("testMethod03", testMethod03),
        ("testMethod04", testMethod04),
        ("testMethod05", testMethod05),
        ("testMethod06", testMethod06),
        ("testMethod07", testMethod07),
    ]
}

extension DITranquillityTests_Parent {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DITranquillityTests_Parent = [
        ("test01_Resolve", test01_Resolve),
        ("test02_ParentResolve_Post", test02_ParentResolve_Post),
        ("test02_ParentResolve_Pre", test02_ParentResolve_Pre),
        ("test03_NotResolve", test03_NotResolve),
        ("test04_ParentNotResolve", test04_ParentNotResolve),
        ("test05_PriorityResolve", test05_PriorityResolve),
        ("test06_Many", test06_Many),
        ("test07_Inject", test07_Inject),
    ]
}

extension DITranquillityTests_Resolve {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DITranquillityTests_Resolve = [
        ("test01_ResolveByClass", test01_ResolveByClass),
        ("test01_ResolveOptional", test01_ResolveOptional),
        ("test02_ResolveByProtocol", test02_ResolveByProtocol),
        ("test03_ResolveByClassAndProtocol", test03_ResolveByClassAndProtocol),
        ("test04_ResolveWithInitializerResolve", test04_ResolveWithInitializerResolve),
        ("test05_ResolveWithDependencyResolveOpt", test05_ResolveWithDependencyResolveOpt),
        ("test06_ResolveWithDependencyResolveOptNil", test06_ResolveWithDependencyResolveOptNil),
        ("test07_ResolveWithDependencyResolveImplicitly", test07_ResolveWithDependencyResolveImplicitly),
        ("test08_ResolveMultiplyWithDefault", test08_ResolveMultiplyWithDefault),
        ("test09_ResolveMultiplyWithDefault_Reverse", test09_ResolveMultiplyWithDefault_Reverse),
        ("test10_ResolveMultiplyByName", test10_ResolveMultiplyByName),
        ("test10_ResolveMultiplyByTag", test10_ResolveMultiplyByTag),
        ("test11_ResolveMultiplySingleByName", test11_ResolveMultiplySingleByName),
        ("test11_ResolveMultiplySingleByTag", test11_ResolveMultiplySingleByTag),
        ("test12_ResolveMultiplyMany", test12_ResolveMultiplyMany),
        ("test12_ResolveMultiplyManyOrder", test12_ResolveMultiplyManyOrder),
        ("test13_ResolveCircular2", test13_ResolveCircular2),
        ("test13_ResolveCircular2WithPerRun", test13_ResolveCircular2WithPerRun),
        ("test14_ResolveCircular3", test14_ResolveCircular3),
        ("test15_ResolveCircularDouble2A", test15_ResolveCircularDouble2A),
        ("test15_ResolveCircularDouble2B", test15_ResolveCircularDouble2B),
        ("test16_ResolveCircularDoubleOneDependency2_WithoutCycle", test16_ResolveCircularDoubleOneDependency2_WithoutCycle),
        ("test17_DependencyIntoDependency", test17_DependencyIntoDependency),
        ("test18_ResolveManyWithNamesTags", test18_ResolveManyWithNamesTags),
        ("test19_resolvePerContainer", test19_resolvePerContainer),
        ("test19_resolvePerContainerUseFunc", test19_resolvePerContainerUseFunc),
        ("test20_ResolveByTagAndTag", test20_ResolveByTagAndTag),
        ("test20_ResolveByTagAndTagShort", test20_ResolveByTagAndTagShort),
        ("test21_ResolveByTagAndMany", test21_ResolveByTagAndMany),
        ("test22_ResolveByTagTagAndMany", test22_ResolveByTagTagAndMany),
        ("test22_ResolveByTagTagAndManyShort", test22_ResolveByTagTagAndManyShort),
        ("test23_ResolveByTagTagTagShort", test23_ResolveByTagTagTagShort),
        ("test24_ResolveUseKeyPath", test24_ResolveUseKeyPath),
        ("test24_ResolveUseKeyPathAndModificators", test24_ResolveUseKeyPathAndModificators),
        ("test24_ResolveUseKeyPathWithCycle", test24_ResolveUseKeyPathWithCycle),
        ("test25_PostInit", test25_PostInit),
        ("test25_PostInitCycle", test25_PostInitCycle),
        ("test26_many", test26_many),
        ("test27_crashLogNilRegister", test27_crashLogNilRegister),
    ]
}

extension DITranquillityTests_ResolveByInit {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DITranquillityTests_ResolveByInit = [
        ("test01_UseRegister", test01_UseRegister),
        ("test02_UseRegisterWithProtocol", test02_UseRegisterWithProtocol),
        ("test03_ResolveMultiplyMany", test03_ResolveMultiplyMany),
        ("test04_RegisterAllParams", test04_RegisterAllParams),
    ]
}

extension DITranquillityTests_SwiftLazy {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DITranquillityTests_SwiftLazy = [
        ("test01_Lazy", test01_Lazy),
        ("test02_Provide", test02_Provide),
        ("test03_LazyMany", test03_LazyMany),
        ("test04_ProviderMany", test04_ProviderMany),
        ("test05_CycleTest", test05_CycleTest),
        ("test06_LazyCycleTest", test06_LazyCycleTest),
        ("test07_ProvideCycleTest", test07_ProvideCycleTest),
        ("test08_LazyOptional", test08_LazyOptional),
        ("test08_LazyOptionalNil", test08_LazyOptionalNil),
        ("test09_LazyInject", test09_LazyInject),
        ("test10_ProviderInject", test10_ProviderInject),
        ("test11_Provider1", test11_Provider1),
        ("test11_Provider2", test11_Provider2),
        ("test11_Provider3", test11_Provider3),
    ]
}

extension DITranquillityTests_Threads {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DITranquillityTests_Threads = [
        ("test01_ResolvePrototype", test01_ResolvePrototype),
        ("test02_ResolveLazySingle", test02_ResolveLazySingle),
        ("test03_ResolveSingle", test03_ResolveSingle),
        ("test04_ResolveRegister", test04_ResolveRegister),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DITranquillityTests_Build.__allTests__DITranquillityTests_Build),
        testCase(DITranquillityTests_Extensions.__allTests__DITranquillityTests_Extensions),
        testCase(DITranquillityTests_Lifetime.__allTests__DITranquillityTests_Lifetime),
        testCase(DITranquillityTests_MoreParameters.__allTests__DITranquillityTests_MoreParameters),
        testCase(DITranquillityTests_Parent.__allTests__DITranquillityTests_Parent),
        testCase(DITranquillityTests_Resolve.__allTests__DITranquillityTests_Resolve),
        testCase(DITranquillityTests_ResolveByInit.__allTests__DITranquillityTests_ResolveByInit),
        testCase(DITranquillityTests_SwiftLazy.__allTests__DITranquillityTests_SwiftLazy),
        testCase(DITranquillityTests_Threads.__allTests__DITranquillityTests_Threads),
    ]
}
#endif
